---
- hosts: all
  vars:
  - default_container_name: docker
  - create_containers: "{{CONTAINER_COUNT|default('4')}}"
  - default_container_image: "{{CONTAINER_NAME|default('ubuntu')}}"
  - default_container_command: "{{CONTAINER_CMD|default('sleep 1d')}}"
    
  tasks:
  - name: Install Docker
    become: yes
    yum: 
      name: docker 
      state: latest
    
  - name: Start and enable the Docker daemon
    become: yes
    service: name=docker state=started enabled=yes
  
  - name: Enable EPEL Repository on CentOS 7
    become: yes
    yum:
      name: epel-release
      state: latest
    
  - name: Install pip
    become: yes
    yum: name=python-pip
    
  - name: Install Docker Module for Python via pip
    become: yes
    pip:
      name: docker
  
  - name: Install Parse Module for Python
    become: yes
    pip:
      name: parse
   
