---
- hosts: all
  vars:
  - default_container_name: docker
  - create_containers: "{{CONTAINER_COUNT|default('4')}}"
  - default_container_image: "{{CONTAINER_NAME|default('ubuntu')}}"
  - default_container_command: "{{CONTAINER_CMD|default('sleep 1d')}}"


  tasks:
  - name: Enable EPEL Repository on CentOS 7
    become: yes
    yum:
      name: epel-release
      state: latest
      
  - name: Add repository
    become: yes
    yum_repository:
      name: docker-ce
      description: docker-ce repo
      baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
      
  - name: Install Docker
    become: yes
    yum: 
      name: docker-ce 
      disable_gpg_check: yes
      state: latest
    
  - name: Start and enable the Docker daemon
    become: yes
    service: name=docker state=started enabled=yes
     
  - name: Install pip
    become: yes
    yum: name=python-pip 
    
  - name: Install Docker Module for Python via pip
    become: yes
    pip:
      name: docker
      executable: pip
      
  - name: Pull default Docker image
    become: yes
    ansible.builtin.shell:
      cmd: docker pull "{{ default_container_image }}"
        
  - name: Create default containers
    become: yes
    ansible.builtin.shell:
      cmd: docker run -d "{{ default_container_image }}" "{{default_container_command}}"
