---
- hosts: all
  vars:
  - default_container_name: docker
  - create_containers: "{{CONTAINER_COUNT|default('4')}}"
  - default_container_image: "{{CONTAINER_NAME|default('ubuntu')}}"
  - default_container_command: "{{CONTAINER_CMD|default('sleep 1d')}}"
    
  tasks:
  - name: Install Docker
    become: yes
    yum: 
      name: docker 
      state: latest
    
  - name: Start and enable the Docker daemon
    become: yes
    service: name=docker state=started enabled=yes
  
  - name: Enable EPEL Repository on CentOS 7
    become: yes
    yum:
      name: epel-release
      state: latest
    vars:
      ansible_python_interpreter: /usr/bin/python
    
  - name: Install pip
    become: yes
    yum: name=python-pip
    vars:
      ansible_python_interpreter: /usr/bin/python   
   
  - name: Install docker-compose
    become: yes
    pip: name=docker-compose version=1.8.1
    vars:
      ansible_python_interpreter: /usr/bin/python
      
  - name: fix requests
    become: yes
    pip: name=requests version=2.12.1 state=forcereinstall
    vars:
      ansible_python_interpreter: /usr/bin/python
    
  - name: Install Docker Module for Python via pip
    become: yes
    pip:
      name: docker
      version: 4.4.4
    vars:
      ansible_python_interpreter: /usr/bin/python
   
  - name: Pull default Docker image
    become: yes
    docker_image:
      name: "{{ default_container_image }}"
      source: pull
    vars:
      ansible_python_interpreter: /usr/bin/python

            
  - name: Create default containers
    become: yes
    docker_container:
      name: "container{{item}}"
      image: "{{ default_container_image }}"
      command: "{{ default_container_command }}"
      state: started
    with_sequence: count="{{ create_containers }}" 
